# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9170a879c393b7889875076cfdb24ff687752cdc9d4edfba8d83efa6f65daf95e7804ff03985dc5094db3b2320c0289efa583e0d05d09af5da521baeb1f3246

test:
  secret_key_base: 4b276ecc815fdaf085f37bfb392388a9d11e7fd24865c3e3af204fae349fabd3e018c14950a4714b394b048fcd10003e16a76d8430ba4519b07b204d5cbac841

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
